apiVersion: "v1"
kind: Pod
metadata:
     name: fitnesse
     labels:
       name: fitnesse
       app: demo
spec:
   containers:
       - name: fitnesse
         image: sgamage/fitnesse
         ports:
           - containerPort: 8080
             name: http
             protocol: TCP
