apiVersion: "v1"
kind: Service
metadata:
    name: fitnesse
    labels:
       name: fitnesse
       app: demo
spec:
        selector:
           name: fitnesse
        type: NodePort
        ports:
          - port: 8080
            targetPort: 8080
            protocol: TCP
